# Generated by Django 4.2 on 2023-08-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_tilte_blogpost_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='tilee',
        ),
    ]
