# Generated by Django 4.2 on 2023-08-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_title_blogpost_tilee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='tilee',
            new_name='title',
        ),
    ]
